### File containing input variables to be parsed by following github workflows.
### Some keys are set by default in cicd repo, specifying them in this file will overwrite end values.
### Inputs file is 'branch sensitive' - eg. if running a workflow based on branch x - inputs file from branch x will be used. (opposite to workflows)

namespace: bankai
app_names: ["bankai-daemon", "bankai-api"]
dockerhub_project: dataprocessor    
etcd_key: .env.stage
version_file: ./Cargo.toml
pull_etcd_config: true