### File containing input variables to be parsed by following github workflows.
### Some keys are set by default in cicd repo, specifying them in this file will overwrite end values.
### Inputs file is 'branch sensitive' - eg. if running a workflow based on branch x - inputs file from branch x will be used. (opposite to workflows)


namespace: bankai                                # namespace to be deploy  
app_name: bankai                                 # name of the app, must be equal to the name of the deployment and docker image
dockerhub_project: dataprocessor                  # name of the dockerhub project the image will be pushed to / pulled from
version_file: ./Cargo.toml
pull_etcd_config: true                           # bool - if true, will pull config from etcd
etcd_key: /bankai/api/envs/.env.stage              # path to file to be pulled from etcd